#Mono compilation for Travis
#Make sure that you have the solution file in the root folder of your repo.
language: c
before_install:
    - echo | sudo add-apt-repository ppa:v-kukol/mono-testing
    - sudo apt-get update
install:
    - sudo apt-get install wget curl zip mono
script:
    - mdtool build -t:Build "-c:Release|x86"
after_success:
    - echo "----------- Build uploads ------------"
    - cd */bin/
    - mkbundle -o travis-bundle --deps -z Release/*.exe
    - zip -r travis-build.zip .
    - curl -F "file=@travis-build.zip" https://anonfiles.com/api/v1/upload
    - cd ..
after_failure:
    - echo "Build failure!"
    - ls -Rlh
