#Mono compilation for Travis
#Make sure that you have the solution file in the root folder of your repo.
language: c
before_install:
    - echo | sudo add-apt-repository ppa:v-kukol/mono-testing
    - sudo apt-get update
install:
    - sudo apt-get install wget curl zip mono-devel
script:
    - xbuild /p:Configuration=Release
    - xbuild /p:Configuration=Debug
    - cd */bin/; mkdir GNULinuxBundle; cd GNULinuxBundle
    - mkbundle -o travis-bundle-release --deps -z ../Release/*.exe
    - mkbundle -o travis-bundle-debug --deps -z ../Debug/*.exe
    - cd ..
    - zip -r - . | curl -F "file=@-" https://anonfiles.com/api/v1/upload > upload.log
    - echo >> upload.log
after_success:
    - echo "----------- Build upload ------------"
    - cat upload.log
after_failure:
    - echo "Build failure!"
    - ls -Rlh
